apiVersion: v1
kind: Service
metadata:
  name: {{ include "intentgate.gateway.fullname" . }}
  labels:
    {{- include "intentgate.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- if or .Values.gateway.service.annotations .Values.gateway.metrics.enabled }}
  annotations:
    {{- if .Values.gateway.metrics.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.gateway.service.port | quote }}
    prometheus.io/path: "/metrics"
    {{- end }}
    {{- with .Values.gateway.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "intentgate.gateway.matchLabels" . | nindent 4 }}
